### ISSUE TITLE
Finish port to Command Context

### ISSUE THREAD

**Issue by 1Revenger1** [Wylx-Bot/Wylx#33]
- [ ] Store Text Channel?

**Comment by SnakeJ419** [comment]
- [ ] Store message object
- [ ] Change authorID/guildID to author/guild objs?
- [ ] Top level sendMessage/reply methods?
- [ ] Reference to the servers DB/built in method that will get the servers DB

**Comment by SnakeJ419** [comment]
Command context already contains enough, I think adding more information would just increase processing time without increasing effeciency
