### ISSUE TITLE
;queuerestart

### ISSUE THREAD

**Issue by SnakeJ419** [Wylx-Bot/Wylx#55]
make a variant of the restart command that ensures wylx isnt actively doing something before it restarts. normal ;restart should continue to exist to force updates for things that need to be fixed imediatly but should now come with a warning to ensure the dev actually wants to restart now instead of waiting for the bot to finish whatever its doing
"doing something" includes:

- currently playing music in a server
- in the middle of a threaded command
- mid fight

Command should also tell the user what the blocking thing was so dev can decide if they want to just force a restart anyways.

**Comment by 1Revenger1** [comment]
I think immediate restart is fine, but we should figure out how to save track information and send a message if the bot is playing something.

I'm not concerned about it being mid fight, as it doesn't save anything until the end of the fight, so worst case scenario, we lose maybe ~30 seconds of data. We can tell users what happened in the middle of a fight too.

**Comment by SnakeJ419** [comment]
To complicated of an idea to actually do, maybe someday
