### ISSUE TITLE
Wibbly Wobbly Time Bits

### ISSUE THREAD

**Issue by SnakeJ419** [Wylx-Bot/Wylx#59]
- [x] Allows users to set their timezone
- [x] Detects times in any messages sent and converts to the timezones of all users in the server

**Comment by SnakeJ419** [comment]
@1Revenger1 are we ***sure*** that we want this enabled by default

**Comment by 1Revenger1** [comment]
@SnakeJ419 I think so. Users have to setup timezones in the first place, and we can notify about the time zone not being set just the first time each user posts a time if we want.

**Comment by SnakeJ419** [comment]
@1Revenger1 I was thinking it might just be best to not notify at all? Not sure how spamy it'll be when it first gets added. Maybe we could limit it to once per server?

**Comment by 1Revenger1** [comment]
@SnakeJ419 it'd only be the first time each user specifies a time, so idk. Could do it once per server, but thej most people might not set it up, idk.

**Comment by SnakeJ419** [comment]
@1Revenger1 yeah but I'm thinking of things like the pnw frc server, although I guess people aren't saying times that often? Do you have server admins you could ask about it? Ig that time is also probably something that kind of server would turn off
